### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by bouguila** [Starcounter/Images#148]
- unable to start the app. (build is fine)
- unable to access the app from main endpoint `Images`  (seems like infinite recursive call)
- accessing via to `images/partials/images` and clickin `add` button will result on nothing other than appending `/images` to the URL (some clicks will result in such `images/partials/images/images/images/images/images/images/images/images/images...`)

### Steps to reproduce
- clone the commit fd2e89a92744020e62f22d1c65ffa39721a7bfe1 (last commit to master before i merge some changes)
- build and run the app
### Expected result
images app should run in default db and should be accessible via http://localhost:8080/images
### Actual result
images app does not run and throws this error:
``` System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: When adding a blending at least one direction converter should be specified.
   at Starcounter.Blender.MapUriInternal(String uri, String blendingToken, Func`2 fromUriConverter, Func`2 toUriConverter, String[] contexts) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter\Apps\Blender.cs:line 604
   at Starcounter.Blender.PopulateBlendings(IEnumerable`1 blendings) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter\Apps\Blender.cs:line 674
   at Starcounter.Blender.PopulateFromJsonFile(String pathToJsonFile) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter\Apps\Blender.cs:line 701
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 277
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 139
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 53
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-17632\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 90
ParamName=When adding a blending at least one direction converter should be specified.
HResult=-2146233086 
```
### Technical information
the error can be fixed adding  
```
"AllowFromDirection": true,
"AllowToDirection": true
```
to the objects lacking it in `blender.json` file, this will fix the start up error BUTwon't fix the isssue accessing the app via `http://localhost:8080/images`

**Comment by bouguila** [comment]
ping @Mihaiii since you're the one who made latest changes to the app.
cc @habib535

**Comment by bouguila** [comment]
@mihai i already mentioned the fix for the blender.json.
but what about the other issues? (check above on the issue description)

PS: it's better to test before merging so you won't catch any responsibility of code dysfunction
